var stir = stir || {}; stir.t4Globals = stir.t4Globals || {};
stir.t4Globals.search = { combos: '/media/stirling/feeds/combo.json' };
stir.t4Globals.search.facets = {
	"Start date": {
		"2025-10AY2025-26": "October 2025",
		"2026-01AY2025-26": "January 2026",
		"2026-06AY2025-26": "June 2026",
		"2026-08AY2026-27": "August 2026",
		"2026-09AY2026-27": "September 2026",
		"2026-10AY2026-27": "October 2026",
		"2027-01AY2026-27": "January 2027"
	},
	"Level": {
		"undergraduate": "Undergraduate",
		"postgraduate (taught)": "Postgraduate taught",
		"postgraduate (research)": "Postgraduate research",
		"module": "CPD and short courses"
	},
	"Delivery mode": {
		"blended": "Blended",
		"on campus": "On campus",
		"online": "Online"
	},
	"Study mode": {
		"full time": "Full time",
		"part time": "Part time",
		"discontinuous": "Discontinuous"
	},
	"Faculty": {
		"faculty of arts and humanities": "Faculty of Arts and Humanities",
		"faculty of health sciences and sport": "Faculty of Health Sciences and Sport",
		"faculty of natural sciences": "Faculty of Natural Sciences",
		"faculty of social sciences": "Faculty of Social Sciences",
		"stirling business school": "Stirling Business School",
		"accounting & finance": "Accounting and Finance",
		"administration": "Administration",
		"ah management and support team": "Arts and Humanities (Management and Support)",
		"biological and environmental sciences": "Biological and Environmental Sciences",
		"checr": "CHeCR",
		"communications, media and culture": "Communications, Media and Culture",
		"computing science": "Computing Science",
		"computing science and mathematics - division": "Computing Science and Mathematics",
		"dementia and ageing": "Dementia and Ageing",
		"dementia services development centre": "Dementia Services Development Centre",
		"economics": "Economics",
		"education": "Education",
		"english studies": "English Studies",
		"fhss management and support": "Faculty of Health Sciences and Sport (Management and Support)",
		"french": "French",
		"health sciences (highland & w.isles)": "Health Sciences (Highland & Western Isles)",
		"health sciences highland": "Health Sciences (Highland)",
		"health sciences stirling": "Health Sciences (Stirling)",
		"history": "History",
		"history and politics - division": "History and Politics",
		"housing studies": "Housing Studies",
		"institute for social marketing": "Institute for Social Marketing",
		"institute of aquaculture": "Institute of Aquaculture",
		"law": "Law",
		"law and philosophy - division": "Law and Philosophy",
		"library and archives research support": "Library and Archives Research Support",
		"literature and languages - division": "Literature and Languages",
		"machrihanish": "Machrihanish",
		"management, work and organisation": "Management, Work and Organisation",
		"marketing & retail": "Marketing and Retail",
		"mathematics": "Mathematics",
		"nmahp": "NMAHP",
		"ns management and support": "Natural Sciences (Management and Support)",
		"philosophy": "Philosophy",
		"politics": "Politics",
		"psychology": "Psychology",
		"religion": "Religion",
		"sbs management and support": "Stirling Business School (Management and Support)",
		"scotland's international environment centre": "Scotland's International Environment Centre",
		"social work": "Social Work",
		"sociology, social policy & criminology": "Sociology, Social Policy and Criminology",
		"spanish": "Spanish",
		"sport": "Sport",
		"university of stirling": "University of Stirling"
	},
	"Subject": [
		"Accounting and finance",
		"Aquaculture",
		"Biology",
		"Business and management",
		"Computer science and software engineering",
		"Criminology",
		"Data science and data analytics",
		"Economics",
		"English and literature",
		"Environmental science",
		"Film and media studies",
		"Geography",
		"Health and allied subjects",
		"History",
		"Humanities",
		"Journalism and publishing",
		"Languages and TESOL",
		"Law",
		"Marketing and public relations",
		"Mathematics",
		"Nursing",
		"Philosophy and religion",
		"Politics",
		"Psychology",
		"Social studies",
		"Sport",
		"Teaching and education"
	],
	"Clearing": {
		"scotland": "Scotland and EU",
		"rukroi": "England, Wales, Northern Ireland and the Republic of Ireland",
		"international": "International",
		"simd": "SIMD"
	},
	"Topic": {
		"ageing-dementia": "Ageing and dementia",
		"alumni": "Alumni",
		"aqua-food": "Aquaculture, food and farming",
		"art-collection": "Art Collection",
		"arts-archives": "Arts and archives",
		"business-economics": "Business and economics",
		"covid-19": "COVID-19",
		"education": "Education",
		"environment": "Environment, climate change and wildlife",
		"graduation": "Graduation",
		"health": "Health",
		"history": "History",
		"history-heritage": "History and heritage",
		"institute-aquaculture": "Institute of Aquaculture",
		"internal-students": "Internal students",
		"policy-hub": "Policy Hub",
		"politics-policy": "Politics, policy and society",
		"ref-2029": "REF 2029",
		"research": "Research",
		"sports": "Sports",
		"sports-centre": "Sports Centre",
		"technology": "Technology",
		"water-quality": "Water quality"
	},
	"SDGs": [
		"Goal 1 No poverty",
		"Goal 2 Zero hunger",
		"Goal 3 Good health and well-being",
		"Goal 4 Quality education",
		"Goal 5 Gender equality",
		"Goal 6 Clean water and sanitation",
		"Goal 7 Affordable and clean energy",
		"Goal 8 Decent work and economic growth",
		"Goal 9 Industry, innovation and infrastructure",
		"Goal 10 Reduced inequalities",
		"Goal 11 Sustainable cities and communities",
		"Goal 12 Responsible consumption and production",
		"Goal 13 Climate action",
		"Goal 14 Life below water",
		"Goal 15 Life on land",
		"Goal 16 Peace, justice and strong institutions",
		"Goal 17 Partnerships for the goals"
	]
};
